# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

conditions = Condition.create!([
  {
    "name": "Blinded",
    "description": "A blinded creature can't see and automatically fails any ability check that requires sight.\n Attack rolls against the creature have advantage. and the creature's atlack ralls have disadvantage.",
    "page": "PHB 290"
  },{
    "name": "Charmed",
    "description": "A charmed creature can't attack the charmer or target the charmer with harmful abilities or magical effects.\n The charmer has advantage on any ability check to interact socially with the creature.",
    "page": "PHB 290"
  },{
    "name": "Deafened",
    "description": "A deafened creature can't hear and automatically fails
    any ability check that requires hearing.",
    "page": "PHB 290"
  },{
    "name": "Frightened",
    "description": "A frightened creature has disadvantage on ability checks and attack rolls while the source of its fear is within line of sight.\n The creature can't willingly move closer to the source of its fear.",
    "page": "PHB 290"
  },{
    "name": "Grappled",
    "description": "A grappled creature's speed becomes O,and it can't benefit from any bonus to its speed.\n  The condition ends if the grappler is incapacitated (see the condition).\n The condition also ends if an effect removes the grappled creature fram the reach of the grappler or grappling effect, such as when a creature is hurled away by the Thunderwave spell.",
    "page": "PHB 290"
  },{
    "name": "Incapacitated",
    "description": "An incapacitated creature can't take actions or reactions.",
    "page": "PHB 290"
  },{
    "name": "Invisible",
    "description": "An invisible creature is impossible to see without the aid of magic or a special sense. For the purpose of hiding, the creature is heavily obscured. The creature's location can be detected by any noise it makes or any tracks it leaves.\n Attack rolls against the creature have disadvantage, and the creature's attack rolls have advantage.",
    "page": "PHB 291"
  },{
    "name": "Paralyzed",
    "description": "A paralyzed creature is Incapacitated (see the condition) and can't move or speak.\n The creature automatically fails Strength and Dexterity saving throws.\n Attack rolls against the creature have advantage.\n Any attack that hits the creature is a critical hit if the attacker is within 5 feet of the creature.",
    "page": "PHB 291"
  },{
    "name": "Petrified",
    "description": "A petrified creature is transformed, along with any nonmagical object it is wearing or carrying, into a solid inanimate substance (usually stone). Its weight increases by a factor of ten, and it ceases aging.\n The creature is Incapacitated (see the condition), can't move or speak, and is unaware of its surroundings.\n Attack rolls against the creature have advantage.\n The creature automatically fails Strength and Dexterity saving throws.\n The creature has resistance to all damage.\n The creature is immune to poison and disease, although a poison or disease already in its system is suspended, not neutralized.",
    "page": "PHB 291"
  },{
    "name": "Poisoned",
    "description": "A poisoned creature has disadvantage on attack rolls and ability checks.",
    "page": "PHB 292"
  },{
    "name": "Prone",
    "description": "A prone creature's only movement option is to crawl, unless it stands up and thereby ends the condition.\n The creature has disadvantage on attack rolls.\n An attack roll against the creature has advantage if the attacker is within 5 feet of the creature. Otherwise, the attack roll has disadvantage.",
    "page": "PHB 292"
  },{
    "name": "Restrained",
    "description": "A restrained creature's speed becomes 0, and it can't benefit from any bonus to its speed.\n Attack rolls against the creature have advantage,
    and the creature's attack rolls have disadvantage.\n The creature has disadvantage on Dexterity saving throws.",
    "page": "PHB 292"
  },{
    "name": "Stunned",
    "description": "A stunned creature is Incapacitated (see the condition), can't move, and can speak only falteringly.\n The creature automatically fails Strength and Dexterity saving throws.\n Attack rolls against the creature have advantage.",
    "page": "PHB 292"
  },{
    "name": "Unconscious",
    "description": "An unconscious creature is Incapacitated (see the condition), can't move or speak, and is unaware of its surroundings.\n The creature drops whatever it's holding and falls Prone.\n The creature automatically fails Strength and Dexterity saving throws.\n Attack rolls against the creature have advantage.\n Any attack that hits the creature is a critical hit if the attacker is within 5 feet of the creature.",
    "page": "PHB 292"
  }
])

user = User.create!({
  "username": "mattMercer",
  "email": "matt@critrole.com",
  "password": "123456",
  "image": "https://upload.wikimedia.org/wikipedia/commons/2/27/Matthew_Mercer_by_Gage_Skidmore.jpg"
})

rest = Rest.create!([
  {
    "name": "Short Rest",
    "description": "A short rest is a period of downtime, at least 1 hour long, during which a character does nothing more strenuous than eating, drinking, reading, and tending to wounds. \n A character can spend one or more Hit Dice at the end of a short rest, up to the character's maximum number of Hit Dice, which is equal to the character's level. For each Hit Die spent in this way, the player rolls the die and adds the character's Constitution modifier to it. The character regains hit points equal to the total. The player can decide to spend an additional Hit Die after each roll. A character regains some spent Hit Dice upon finishing a long rest, as explained below.",
    "page": "PHB 168"
  },{
    "name": "Long Rest",
    "description": "A long rest is a period of extended downtime, at least 8 hours long, during which a character sleeps or performs light activity: reading, talking, eating, or standing watch for no more than 2 hours. If the rest is interrupted by a period of strenuous activity---at least 1 hour of walking, fighting, casting spells, or similar adventuring activity---the characters must begin the rest again to gain any benefit from it. \n At the end of a long rest, a character regains all lost hit points. The character also regains spent Hit Dice, up to a number of dice equal to half of the character's total number of them (minimum of one die). For example, if a character has eight Hit Dice, he or she can regain four spent Hit Dice upon finishing a long rest. \n A character can't benefit from more than one long rest in a 24-hour period, and a character must have at least 1 hit point at the start of the rest to gain its benefits.",
    "page": "PHB 168"
  }
])

rest = Spell.create!([
  {
    "name": "Acid Splash",
    "description": "You hurl a bubble of acid. Choose one creature within range, or choose two creatures within range that are within 5 feet of each other. A target must succeed on a dexterity saving throw or take 1d6 acid damage. This spell's damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).",
    "higher_level": "",
    "page": "PHB 211",
    "range": "60 feet",
    "components": "V, S",
    "material": "",
    "ritual": false,
    "duration": "Instantaneous",
    "concentration": false,
    "casting_time": "1 action",
    "level": "Cantrip",
    "level_int": 0,
    "school": "Conjuration",
    "dnd_class": "Sorcerer, Wizard",
    "archetype": "",
    "circles": "",
  },
  {
    "name": "Chill Touch",
    "description": "You create a ghostly, skeletal hand in the space of a creature within range. Make a ranged spell attack against the creature to assail it with the chill of the grave. On a hit, the target takes 1d8 necrotic damage, and it can't regain hit points until the start of your next turn. Until then, the hand clings to the target. If you hit an undead target, it also has disadvantage on attack rolls against you until the end of your next turn. This spell's damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).",
    "higher_level": "",
    "page": "PHB 221",
    "range": "120 feet",
    "components": "V, S",
    "material": "",
    "ritual": false,
    "duration": "1 round",
    "concentration": false,
    "casting_time": "1 action",
    "level": "Cantrip",
    "level_int": 0,
    "school": "Necromancy",
    "dnd_class": "Sorcerer, Warlock, Wizard",
    "archetype": "",
    "circles": ""
},
{
    "name": "Dancing Lights",
    "description": "You create up to four torch-sized lights within range, making them appear as torches, lanterns, or glowing orbs that hover in the air for the duration. You can also combine the four lights into one glowing vaguely humanoid form of Medium size. Whichever form you choose, each light sheds dim light in a 10-foot radius. As a bonus action on your turn, you can move the lights up to 60 feet to a new spot within range. A light must be within 20 feet of another light created by this spell, and a light winks out if it exceeds the spell's range.",
    "higher_level": "",
    "page": "PHB 230",
    "range": "120 feet",
    "components": "V, S, M",
    "material": "A bit of phosphorus or wychwood, or a glowworm.",
    "ritual": false,
    "duration": "Up to 1 minute",
    "concentration": true,
    "casting_time": "1 action",
    "level": "Cantrip",
    "level_int": 0,
    "school": "Evocation",
    "dnd_class": "Bard, Sorcerer, Wizard",
    "archetype": "",
    "circles": "",
},
{
    "name": "Druidcraft",
    "description": "Whispering to the spirits of nature, you create one of the following effects within range: \n- You create a tiny, harmless sensory effect that predicts what the weather will be at your location for the next 24 hours. The effect might manifest as a golden orb for clear skies, a cloud for rain, falling snowflakes for snow, and so on. This effect persists for 1 round. \n- You instantly make a flower blossom, a seed pod open, or a leaf bud bloom. \n- You create an instantaneous, harmless sensory effect, such as falling leaves, a puff of wind, the sound of a small animal, or the faint odor of skunk. The effect must fit in a 5-­‐‑foot cube. \n- You instantly light or snuff out a candle, a torch, or a small campfire.",
    "higher_level": "",
    "page": "PHB 236",
    "range": "30 feet",
    "components": "V, S",
    "material": "",
    "ritual": false,
    "duration": "Instantaneous",
    "concentration": false,
    "casting_time": "1 action",
    "level": "Cantrip",
    "level_int": 0,
    "school": "Transmutation",
    "dnd_class": "Druid",
    "archetype": "",
    "circles": "",
},
{
    "name": "Eldritch Blast",
    "description": "A beam of crackling energy streaks toward a creature within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 force damage. The spell creates more than one beam when you reach higher levels: two beams at 5th level, three beams at 11th level, and four beams at 17th level. You can direct the beams at the same target or at different ones. Make a separate attack roll for each beam.",
    "higher_level": "",
    "page": "PHB 237",
    "range": "120 feet",
    "components": "V, S",
    "material": "",
    "ritual": false,
    "duration": "Instantaneous",
    "concentration": false,
    "casting_time": "1 action",
    "level": "Cantrip",
    "level_int": 0,
    "school": "Evocation",
    "dnd_class": "Warlock",
    "archetype": "",
    "circles": "",
},
{
    "name": "Fire Bolt",
    "description": "You hurl a mote of fire at a creature or object within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 fire damage. A flammable object hit by this spell ignites if it isn't being worn or carried. This spell's damage increases by 1d10 when you reach 5th level (2d10), 11th level (3d10), and 17th level (4d10).",
    "higher_level": "",
    "page": "PHB 242",
    "range": "120 feet",
    "components": "V, S",
    "material": "",
    "ritual": false,
    "duration": "Instantaneous",
    "concentration": false,
    "casting_time": "1 action",
    "level": "Cantrip",
    "level_int": 0,
    "school": "Evocation",
    "dnd_class": "Sorcerer, Wizard",
    "archetype": "",
    "circles": "",
},
{
    "name": "Guidance",
    "description": "You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check of its choice. It can roll the die before or after making the ability check. The spell then ends.",
    "higher_level": "",
    "page": "PHB 248",
    "range": "Touch",
    "components": "V, S",
    "material": "",
    "ritual": false,
    "duration": "Up to 1 minute",
    "concentration": true,
    "casting_time": "1 action",
    "level": "Cantrip",
    "level_int": 0,
    "school": "Divination",
    "dnd_class": "Cleric, Druid",
    "archetype": "",
    "circles": "",
},
{
    "name": "Light",
    "description": "You touch one object that is no larger than 10 feet in any dimension. Until the spell ends, the object sheds bright light in a 20-foot radius and dim light for an additional 20 feet. The light can be colored as you like. Completely covering the object with something opaque blocks the light. The spell ends if you cast it again or dismiss it as an action. If you target an object held or worn by a hostile creature, that creature must succeed on a dexterity saving throw to avoid the spell.",
    "higher_level": "",
    "page": "PHB 255",
    "range": "Touch",
    "components": "V, M",
    "material": "A firefly or phosphorescent moss.",
    "ritual": false,
    "duration": "1 hour",
    "concentration": false,
    "casting_time": "1 action",
    "level": "Cantrip",
    "level_int": 0,
    "school": "Evocation",
    "dnd_class": "Bard, Cleric, Sorcerer, Wizard",
    "archetype": "",
    "circles": "",
},
{
    "name": "Mage Hand",
    "description": "A spectral, floating hand appears at a point you choose within range. The hand lasts for the duration or until you dismiss it as an action. The hand vanishes if it is ever more than 30 feet away from you or if you cast this spell again. You can use your action to control the hand. You can use the hand to manipulate an object, open an unlocked door or container, stow or retrieve an item from an open container, or pour the contents out of a vial. You can move the hand up to 30 feet each time you use it. The hand can't attack, activate magic items, or carry more than 10 pounds.",
    "higher_level": "",
    "page": "PHB 256",
    "range": "30 feet",
    "components": "V, S",
    "material": "",
    "ritual": false,
    "duration": "1 minute",
    "concentration": false,
    "casting_time": "1 action",
    "level": "Cantrip",
    "level_int": 0,
    "school": "Conjuration",
    "dnd_class": "Bard, Sorcerer, Warlock, Wizard",
    "archetype": "",
    "circles": "",
},
{
    "name": "Mending",
    "description": "This spell repairs a single break or tear in an object you touch, such as a broken key, a torn cloak, or a leaking wineskin. As long as the break or tear is no longer than 1 foot in any dimension, you mend it, leaving no trace of the former damage. This spell can physically repair a magic item or construct, but the spell can't restore magic to such an object.",
    "higher_level": "",
    "page": "PHB 259",
    "range": "Touch",
    "components": "V, S, M",
    "material": "Two lodestones.",
    "ritual": false,
    "duration": "Instantaneous",
    "concentration": false,
    "casting_time": "1 minute",
    "level": "Cantrip",
    "level_int": 0,
    "school": "Transmutation",
    "dnd_class": "Cleric, Bard, Druid, Sorcerer, Wizard",
    "archetype": "",
    "circles": "",
},
{
    "name": "Message",
    "description": "You point your finger toward a creature within range and whisper a message. The target (and only the target) hears the message and can reply in a whisper that only you can hear. You can cast this spell through solid objects if you are familiar with the target and know it is beyond the barrier. Magical silence, 1 foot of stone, 1 inch of common metal, a thin sheet of lead, or 3 feet of wood blocks the spell. The spell doesn't have to follow a straight line and can travel freely around corners or through openings.",
    "higher_level": "",
    "page": "PHB 259",
    "range": "120 feet",
    "components": "V, S, M",
    "material": "A short piece of copper wire.",
    "ritual": false,
    "duration": "1 round",
    "concentration": false,
    "casting_time": "1 action",
    "level": "Cantrip",
    "level_int": 0,
    "school": "Transmutation",
    "dnd_class": "Bard, Sorcerer, Wizard",
    "archetype": "",
    "circles": "",
},
{
    "name": "Minor Illusion",
    "description": "You create a sound or an image of an object within range that lasts for the duration. The illusion also ends if you dismiss it as an action or cast this spell again. If you create a sound, its volume can range from a whisper to a scream. It can be your voice, someone else's voice, a lion's roar, a beating of drums, or any other sound you choose. The sound continues unabated throughout the duration, or you can make discrete sounds at different times before the spell ends. If you create an image of an object—such as a chair, muddy footprints, or a small chest—it must be no larger than a 5-foot cube. The image can't create sound, light, smell, or any other sensory effect. Physical interaction with the image reveals it to be an illusion, because things can pass through it. If a creature uses its action to examine the sound or image, the creature can determine that it is an illusion with a successful Intelligence (Investigation) check against your spell save DC. If a creature discerns the illusion for what it is, the illusion becomes faint to the creature.",
    "higher_level": "",
    "page": "PHB 260",
    "range": "30 feet",
    "components": "S, M",
    "material": "A bit of fleece.",
    "ritual": false,
    "duration": "1 minute",
    "concentration": false,
    "casting_time": "1 action",
    "level": "Cantrip",
    "level_int": 0,
    "school": "Illusion",
    "dnd_class": "Bard, Sorcerer, Warlock, Wizard",
    "archetype": "",
    "circles": "",
},
{
    "name": "Poison Spray",
    "description": "You extend your hand toward a creature you can see within range and project a puff of noxious gas from your palm. The creature must succeed on a Constitution saving throw or take 1d12 poison damage. This spell's damage increases by 1d12 when you reach 5th level (2d12), 11th level (3d12), and 17th level (4d12).",
    "higher_level": "",
    "page": "PHB 266",
    "range": "10 feet",
    "components": "V, S",
    "material": "",
    "ritual": false,
    "duration": "Instantaneous",
    "concentration": false,
    "casting_time": "1 action",
    "level": "Cantrip",
    "level_int": 0,
    "school": "Conjuration",
    "dnd_class": "Druid, Sorcerer, Warlock, Wizard",
    "archetype": "",
    "circles": "",
},
{
    "name": "Prestidigitation",
    "description": "This spell is a minor magical trick that novice spellcasters use for practice. You create one of the following magical effects within 'range': \n- You create an instantaneous, harmless sensory effect, such as a shower of sparks, a puff of wind, faint musical notes, or an odd odor. \n- You instantaneously light or snuff out a candle, a torch, or a small campfire. \n- You instantaneously clean or soil an object no larger than 1 cubic foot. \n- You chill, warm, or flavor up to 1 cubic foot of nonliving material for 1 hour. \n- You make a color, a small mark, or a symbol appear on an object or a surface for 1 hour. \n- You create a nonmagical trinket or an illusory image that can fit in your hand and that lasts until the end of your next turn. \nIf you cast this spell multiple times, you can have up to three of its non-instantaneous effects active at a time, and you can dismiss such an effect as an action.",
    "higher_level": "",
    "page": "PHB 267",
    "range": "10 feet",
    "components": "V, S",
    "material": "",
    "ritual": false,
    "duration": "1 hour",
    "concentration": false,
    "casting_time": "1 action",
    "level": "Cantrip",
    "level_int": 0,
    "school": "Transmutation",
    "dnd_class": "Bard, Sorcerer, Warlock, Wizard",
    "archetype": "",
    "circles": "",
},
{
    "name": "Produce Flame",
    "description": "A flickering flame appears in your hand. The flame remains there for the duration and harms neither you nor your equipment. The flame sheds bright light in a 10-foot radius and dim light for an additional 10 feet. The spell ends if you dismiss it as an action or if you cast it again. You can also attack with the flame, although doing so ends the spell. When you cast this spell, or as an action on a later turn, you can hurl the flame at a creature within 30 feet of you. Make a ranged spell attack. On a hit, the target takes 1d8 fire damage. This spell's damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).",
    "higher_level": "",
    "page": "PHB 269",
    "range": "Self",
    "components": "V, S",
    "material": "",
    "ritual": false,
    "duration": "10 minutes",
    "concentration": false,
    "casting_time": "1 action",
    "level": "Cantrip",
    "level_int": 0,
    "school": "Conjuration",
    "dnd_class": "Druid",
    "archetype": "",
    "circles": "",
},
{
    "name": "Ray of Frost",
    "description": "A frigid beam of blue-white light streaks toward a creature within range. Make a ranged spell attack against the target. On a hit, it takes 1d8 cold damage, and its speed is reduced by 10 feet until the start of your next turn. The spell's damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).",
    "higher_level": "",
    "page": "PHB 271",
    "range": "60 feet",
    "components": "V, S",
    "material": "",
    "ritual": false,
    "duration": "Instantaneous",
    "concentration": false,
    "casting_time": "1 action",
    "level": "Cantrip",
    "level_int": 0,
    "school": "Evocation",
    "dnd_class": "Sorcerer, Wizard",
    "archetype": "",
    "circles": "",
},
{
    "name": "Resistance",
    "description": "You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one saving throw of its choice. It can roll the die before or after making the saving throw. The spell then ends.",
    "higher_level": "",
    "page": "PHB 272",
    "range": "Touch",
    "components": "V, S, M",
    "material": "A miniature cloak.",
    "ritual": false,
    "duration": "Up to 1 minute",
    "concentration": true,
    "casting_time": "1 action",
    "level": "Cantrip",
    "level_int": 0,
    "school": "Abjuration",
    "dnd_class": "Cleric, Druid",
    "archetype": "",
    "circles": "",
},
{
    "name": "Sacred Flame",
    "description": "Flame-like radiance descends on a creature that you can see within range. The target must succeed on a dexterity saving throw or take 1d8 radiant damage. The target gains no benefit from cover for this saving throw. The spell's damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).",
    "higher_level": "",
    "page": "PHB 272",
    "range": "60 feet",
    "components": "V, S",
    "material": "",
    "ritual": false,
    "duration": "Instantaneous",
    "concentration": false,
    "casting_time": "1 action",
    "level": "Cantrip",
    "level_int": 0,
    "school": "Evocation",
    "dnd_class": "Cleric",
    "archetype": "",
    "circles": "",
},
{
    "name": "Shillelagh",
    "description": "The wood of a club or a quarterstaff you are holding is imbued with nature's power. For the duration, you can use your spellcasting ability instead of Strength for the attack and damage rolls of melee attacks using that weapon, and the weapon's damage die becomes a d8. The weapon also becomes magical, if it isn't already. The spell ends if you cast it again or if you let go of the weapon.",
    "higher_level": "",
    "page": "PHB 275",
    "range": "Touch",
    "components": "V, S, M",
    "material": "Mistletoe, a shamrock leaf, and a club or quarterstaff.",
    "ritual": false,
    "duration": "1 minute",
    "concentration": false,
    "casting_time": "1 bonus action",
    "level": "Cantrip",
    "level_int": 0,
    "school": "Transmutation",
    "dnd_class": "Druid",
    "archetype": "",
    "circles": "",
},
{
    "name": "Shocking Grasp",
    "description": "Lightning springs from your hand to deliver a shock to a creature you try to touch. Make a melee spell attack against the target. You have advantage on the attack roll if the target is wearing armor made of metal. On a hit, the target takes 1d8 lightning damage, and it can't take reactions until the start of its next turn. The spell's damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).",
    "higher_level": "",
    "page": "PHB 275",
    "range": "Touch",
    "components": "V, S",
    "material": "",
    "ritual": false,
    "duration": "Instantaneous",
    "concentration": false,
    "casting_time": "1 action",
    "level": "Cantrip",
    "level_int": 0,
    "school": "Evocation",
    "dnd_class": "Sorcerer, Wizard",
    "archetype": "",
    "circles": "",
},
{
    "name": "Spare the Dying",
    "description": "You touch a living creature that has 0 hit points. The creature becomes stable. This spell has no effect on undead or constructs.",
    "higher_level": "",
    "page": "PHB 277",
    "range": "Touch",
    "components": "V, S",
    "material": "",
    "ritual": false,
    "duration": "Instantaneous",
    "concentration": false,
    "casting_time": "1 action",
    "level": "Cantrip",
    "level_int": 0,
    "school": "Necromancy",
    "dnd_class": "Cleric",
    "archetype": "",
    "circles": "",
},
{
    "name": "Thaumaturgy",
    "description": "You manifest a minor wonder, a sign of supernatural power, within range. You create one of the following magical effects within range. \n- Your voice booms up to three times as loud as normal for 1 minute. \n- You cause flames to flicker, brighten, dim, or change color for 1 minute. \n- You cause harmless tremors in the ground for 1 minute. \n- You create an instantaneous sound that originates from a point of your choice within range, such as a rumble of thunder, the cry of a raven, or ominous whispers. \n- You instantaneously cause an unlocked door or window to fly open or slam shut. \n- You alter the appearance of your eyes for 1 minute. \nIf you cast this spell multiple times, you can have up to three of its 1-minute effects active at a time, and you can dismiss such an effect as an action.",
    "higher_level": "",
    "page": "PHB 282",
    "range": "30 feet",
    "components": "V",
    "material": "",
    "ritual": false,
    "duration": "1 minute",
    "concentration": false,
    "casting_time": "1 action",
    "level": "Cantrip",
    "level_int": 0,
    "school": "Transmutation",
    "dnd_class": "Cleric",
    "archetype": "",
    "circles": "",
},
{
    "name": "True Strike",
    "description": "You extend your hand and point a finger at a target in range. Your magic grants you a brief insight into the target's defenses. On your next turn, you gain advantage on your first attack roll against the target, provided that this spell hasn't ended.",
    "higher_level": "",
    "page": "PHB 284",
    "range": "30 feet",
    "components": "S",
    "material": "",
    "ritual": false,
    "duration": "Up to 1 round",
    "concentration": true,
    "casting_time": "1 action",
    "level": "Cantrip",
    "level_int": 0,
    "school": "Divination",
    "dnd_class": "Bard, Sorcerer, Warlock, Wizard",
    "archetype": "",
    "circles": "",
},
{
    "name": "Vicious Mockery",
    "description": "You unleash a string of insults laced with subtle enchantments at a creature you can see within range. If the target can hear you (though it need not understand you), it must succeed on a Wisdom saving throw or take 1d4 psychic damage and have disadvantage on the next attack roll it makes before the end of its next turn. This spell's damage increases by 1d4 when you reach 5th level (2d4), 11th level (3d4), and 17th level (4d4).",
    "higher_level": "",
    "page": "PHB 285",
    "range": "60 feet",
    "components": "V",
    "material": "",
    "ritual": false,
    "duration": "Instantaneous",
    "concentration": false,
    "casting_time": "1 action",
    "level": "Cantrip",
    "level_int": 0,
    "school": "Enchantment",
    "dnd_class": "Bard",
    "archetype": "",
    "circles": "",
},
])


p "#{Condition.count} conditions created!"
p "#{User.count} users created!"
p "#{Rest.count} rests created!"
p "#{Spell.count} spells created!"